#!/usr/bin/env python3
"""Rebuild and validate a bookmark-this Markdown hierarchy using stdlib only."""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit


MARKER = "<!-- generated by bookmark-this; do not edit -->"
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TICKER_RE = re.compile(r"^[A-Z0-9._:-]{1,24}$")
MEDIA_TYPES = {"none", "image", "video", "stock"}
EMBED_HOSTS = {"youtube.com", "www.youtube.com", "youtube-nocookie.com", "www.youtube-nocookie.com", "player.vimeo.com", "instagram.com", "www.instagram.com"}
REQUIRED_FIELDS = {
    "title",
    "type",
    "url",
    "canonical_url",
    "domain",
    "captured",
    "tags",
    "categories",
    "status",
}


class SystemError(Exception):
    pass


def load_config(root: Path) -> dict[str, Any]:
    path = root / ".bookmark-system" / "config.json"
    if not path.is_file():
        raise SystemError(f"Missing configuration: {path}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemError(f"Cannot read valid JSON configuration: {exc}") from exc

    if config.get("version") != 1:
        raise SystemError("config.json must contain version 1")
    for key in ("paths", "categories", "capture", "navigation"):
        if key not in config:
            raise SystemError(f"config.json is missing {key!r}")

    paths = config["paths"]
    for key in ("bookmarks", "views", "collections", "index"):
        value = paths.get(key)
        if not isinstance(value, str) or not value.strip():
            raise SystemError(f"paths.{key} must be a non-empty relative path")
        candidate = Path(value)
        if candidate.is_absolute() or ".." in candidate.parts:
            raise SystemError(f"paths.{key} must stay inside the bookmark root")
    if "assets" in paths:
        assets_value = paths["assets"]
        assets_candidate = Path(str(assets_value))
        if not isinstance(assets_value, str) or not assets_value.strip() or assets_candidate.is_absolute() or ".." in assets_candidate.parts:
            raise SystemError("paths.assets must be a non-empty relative path inside the bookmark root")

    category_slugs: set[str] = set()
    for category in config["categories"]:
        if not isinstance(category, dict):
            raise SystemError("Each category must be an object")
        slug = category.get("slug", "")
        if not isinstance(slug, str) or not SLUG_RE.fullmatch(slug):
            raise SystemError(f"Invalid category slug: {slug!r}")
        if slug in category_slugs:
            raise SystemError(f"Duplicate category slug: {slug}")
        category_slugs.add(slug)
        if not category.get("label"):
            raise SystemError(f"Category {slug!r} needs a label")

    if config.get("link_style", "markdown") not in {"markdown", "wikilink"}:
        raise SystemError("link_style must be 'markdown' or 'wikilink'")
    visualizer = config.get("visualizer", {"enabled": False, "path": "visualizer/index.html"})
    if not isinstance(visualizer, dict) or not isinstance(visualizer.get("enabled", False), bool):
        raise SystemError("visualizer must contain a boolean enabled value")
    visualizer_path = Path(str(visualizer.get("path", "visualizer/index.html")))
    if visualizer_path.is_absolute() or ".." in visualizer_path.parts or visualizer_path.suffix.lower() != ".html":
        raise SystemError("visualizer.path must be a relative .html path inside the root")
    context = config.get("context", {"mode": "none", "sources": [], "store_excerpts": False})
    if not isinstance(context, dict) or context.get("mode", "none") not in {"approved", "conversation-only", "none"}:
        raise SystemError("context.mode must be 'approved', 'conversation-only', or 'none'")
    if not isinstance(context.get("sources", []), list):
        raise SystemError("context.sources must be a list")
    if context.get("store_excerpts", False) is not False:
        raise SystemError("context.store_excerpts must remain false")
    ingestion = config.get(
        "ingestion",
        {
            "enabled": False,
            "sources": [],
            "deduplicate": True,
            "preserve_legacy_folders": True,
            "delete_sources": False,
        },
    )
    if not isinstance(ingestion, dict) or not isinstance(ingestion.get("enabled", False), bool):
        raise SystemError("ingestion must contain a boolean enabled value")
    if not isinstance(ingestion.get("sources", []), list):
        raise SystemError("ingestion.sources must be a list")
    for key in ("deduplicate", "preserve_legacy_folders", "delete_sources"):
        if not isinstance(ingestion.get(key), bool):
            raise SystemError(f"ingestion.{key} must be a boolean")
    if ingestion.get("delete_sources") is not False:
        raise SystemError("ingestion.delete_sources must remain false")
    rich_media = config.get(
        "rich_media",
        {
            "enabled": True,
            "cache_preview_images": True,
            "allow_remote_video_embeds": False,
            "allow_remote_stock_charts": False,
            "stock_chart_provider": "tradingview",
        },
    )
    if not isinstance(rich_media, dict):
        raise SystemError("rich_media must be an object")
    for key in ("enabled", "cache_preview_images", "allow_remote_video_embeds", "allow_remote_stock_charts"):
        if not isinstance(rich_media.get(key), bool):
            raise SystemError(f"rich_media.{key} must be a boolean")
    if rich_media.get("stock_chart_provider") not in {"tradingview", "none"}:
        raise SystemError("rich_media.stock_chart_provider must be 'tradingview' or 'none'")
    return config


def parse_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_frontmatter(path: Path) -> dict[str, Any]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise SystemError(f"Cannot read {path}: {exc}") from exc
    if not lines or lines[0].strip() != "---":
        raise SystemError(f"Missing YAML frontmatter in {path}")

    data: dict[str, Any] = {}
    current_list: str | None = None
    for line in lines[1:]:
        if line.strip() == "---":
            return data
        list_match = re.match(r"^\s+-\s+(.+?)\s*$", line)
        if list_match and current_list:
            data[current_list].append(parse_scalar(list_match.group(1)))
            continue
        field_match = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):(?:\s*(.*))?$", line)
        if not field_match:
            if line.strip() and not line.lstrip().startswith("#"):
                current_list = None
            continue
        key, raw_value = field_match.group(1), field_match.group(2) or ""
        if raw_value.strip():
            data[key] = parse_scalar(raw_value)
            current_list = None
        else:
            data[key] = []
            current_list = key
    raise SystemError(f"Unclosed YAML frontmatter in {path}")


def bookmark_records(root: Path, config: dict[str, Any]) -> list[dict[str, Any]]:
    directory = root / config["paths"]["bookmarks"]
    if not directory.exists():
        return []
    records: list[dict[str, Any]] = []
    for path in sorted(directory.rglob("*.md")):
        metadata = parse_frontmatter(path)
        records.append({"path": path, "metadata": metadata})
    return records


def relative_link(root: Path, source: Path, target: Path, title: str, style: str) -> str:
    if style == "wikilink":
        target_from_root = target.relative_to(root).with_suffix("").as_posix()
        return f"[[{target_from_root}|{title}]]"
    relative = os.path.relpath(target, start=source.parent).replace(os.sep, "/")
    return f"[{title}]({relative})"


def bookmark_line(root: Path, source: Path, record: dict[str, Any], style: str) -> str:
    metadata = record["metadata"]
    title = str(metadata.get("title") or record["path"].stem)
    domain = str(metadata.get("domain") or "unknown domain")
    captured = str(metadata.get("captured") or "unknown date")
    link = relative_link(root, source, record["path"], title, style)
    return f"- {link} — {domain} · {captured}"


def write_generated(path: Path, body: str) -> None:
    if path.exists():
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
        if first_line != [MARKER]:
            raise SystemError(f"Refusing to overwrite unmarked file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{MARKER}\n\n{body.rstrip()}\n", encoding="utf-8")


def rebuild(root: Path, config: dict[str, Any]) -> None:
    paths = config["paths"]
    bookmarks_dir = root / paths["bookmarks"]
    views_dir = root / paths["views"]
    collections_dir = root / paths["collections"]
    index_path = root / paths["index"]
    directories = [bookmarks_dir, views_dir / "categories", views_dir / "tags", collections_dir]
    if config.get("rich_media", {}).get("cache_preview_images", False):
        directories.append(root / paths.get("assets", "bookmark-assets"))
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)

    records = bookmark_records(root, config)
    style = config.get("link_style", "markdown")
    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    by_tag: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        metadata = record["metadata"]
        for category in metadata.get("categories", []) if isinstance(metadata.get("categories"), list) else []:
            by_category[str(category)].append(record)
        for tag in metadata.get("tags", []) if isinstance(metadata.get("tags"), list) else []:
            by_tag[str(tag)].append(record)

    categories = config["categories"]
    index_lines = ["# Bookmark index", "", f"{len(records)} saved bookmark{'s' if len(records) != 1 else ''}.", "", "## Browse by category", ""]
    for category in categories:
        slug = category["slug"]
        view_path = views_dir / "categories" / f"{slug}.md"
        link = relative_link(root, index_path, view_path, category["label"], style)
        index_lines.append(f"- {link} ({len(by_category.get(slug, []))}) — {category.get('description', '').strip()}")

    if config["navigation"].get("generate_tag_views", True) and by_tag:
        index_lines.extend(["", "## Browse by tag", ""])
        for tag in sorted(by_tag):
            view_path = views_dir / "tags" / f"{tag}.md"
            link = relative_link(root, index_path, view_path, tag, style)
            index_lines.append(f"- {link} ({len(by_tag[tag])})")

    index_lines.extend(["", "## All bookmarks", ""])
    ordered = sorted(records, key=lambda item: (str(item["metadata"].get("captured", "")), str(item["metadata"].get("title", ""))), reverse=True)
    index_lines.extend(bookmark_line(root, index_path, record, style) for record in ordered)
    if not records:
        index_lines.append("No bookmarks yet.")
    write_generated(index_path, "\n".join(index_lines))

    if config["navigation"].get("generate_category_views", True):
        for category in categories:
            slug = category["slug"]
            view_path = views_dir / "categories" / f"{slug}.md"
            lines = [f"# {category['label']}", "", category.get("description", "").strip(), ""]
            selected = sorted(by_category.get(slug, []), key=lambda item: str(item["metadata"].get("title", "")).lower())
            lines.extend(bookmark_line(root, view_path, record, style) for record in selected)
            if not selected:
                lines.append("No bookmarks in this category yet.")
            write_generated(view_path, "\n".join(lines))

    if config["navigation"].get("generate_tag_views", True):
        for tag, selected in sorted(by_tag.items()):
            if not SLUG_RE.fullmatch(tag):
                continue
            view_path = views_dir / "tags" / f"{tag}.md"
            lines = [f"# {tag}", ""]
            for record in sorted(selected, key=lambda item: str(item["metadata"].get("title", "")).lower()):
                lines.append(bookmark_line(root, view_path, record, style))
            write_generated(view_path, "\n".join(lines))

    print(f"Rebuilt navigation for {len(records)} bookmark(s): {index_path}")


def note_summary(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^## What it is\s*\n+(.*?)(?=\n## |\Z)", text, flags=re.MULTILINE | re.DOTALL)
    if not match:
        return ""
    paragraph = re.split(r"\n\s*\n", match.group(1).strip(), maxsplit=1)[0]
    return re.sub(r"\s+", " ", paragraph).strip()[:280]


def visualize(root: Path, config: dict[str, Any]) -> None:
    visualizer_config = config.get("visualizer", {"enabled": False, "path": "visualizer/index.html"})
    if not visualizer_config.get("enabled", False):
        raise SystemError("The visualizer is disabled in config.json")
    output = root / visualizer_config.get("path", "visualizer/index.html")
    output.parent.mkdir(parents=True, exist_ok=True)
    categories = {item["slug"]: item["label"] for item in config["categories"]}
    records = bookmark_records(root, config)
    items: list[dict[str, Any]] = []
    for record in records:
        metadata = record["metadata"]
        note_path = os.path.relpath(record["path"], start=output.parent).replace(os.sep, "/")
        items.append(
            {
                "title": str(metadata.get("title") or record["path"].stem),
                "url": str(metadata.get("url") or ""),
                "domain": str(metadata.get("domain") or ""),
                "captured": str(metadata.get("captured") or ""),
                "categories": metadata.get("categories", []) if isinstance(metadata.get("categories"), list) else [],
                "tags": metadata.get("tags", []) if isinstance(metadata.get("tags"), list) else [],
                "summary": note_summary(record["path"]),
                "note": note_path,
            }
        )
    payload = json.dumps(
        {
            "items": items,
            "categories": categories,
            "ownerLabel": config.get("owner_label", "you"),
            "platform": config.get("agentic_platform", ""),
        },
        ensure_ascii=False,
    ).replace("<", "\\u003c")
    document = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Bookmark library</title>
  <style>
    :root {{ color-scheme: light; --ink:#18211c; --muted:#657068; --paper:#f4f1e8; --card:#fffdf7; --line:#d8d5ca; --accent:#176b4d; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; background:var(--paper); color:var(--ink); font:15px/1.5 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }}
    main {{ width:min(1180px,calc(100% - 32px)); margin:0 auto; padding:48px 0 72px; }}
    header {{ display:grid; grid-template-columns:1fr auto; gap:24px; align-items:end; border-bottom:1px solid var(--line); padding-bottom:24px; }}
    h1 {{ margin:0; font:700 clamp(34px,6vw,72px)/.95 Georgia,serif; letter-spacing:-.04em; }}
    .eyebrow {{ color:var(--accent); font-size:12px; font-weight:800; letter-spacing:.12em; text-transform:uppercase; margin-bottom:10px; }}
    .count {{ color:var(--muted); white-space:nowrap; }}
    .controls {{ display:grid; grid-template-columns:minmax(220px,1fr) auto; gap:12px; margin:24px 0 12px; }}
    input {{ width:100%; border:1px solid var(--line); background:var(--card); color:var(--ink); border-radius:8px; padding:13px 14px; font:inherit; }}
    button {{ border:1px solid var(--line); background:transparent; color:var(--ink); border-radius:999px; padding:8px 13px; cursor:pointer; }}
    button.active {{ border-color:var(--accent); background:var(--accent); color:white; }}
    .filters {{ display:flex; gap:8px; flex-wrap:wrap; margin:0 0 28px; }}
    .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:14px; }}
    article {{ min-height:220px; display:flex; flex-direction:column; background:var(--card); border:1px solid var(--line); padding:20px; }}
    article h2 {{ margin:8px 0 10px; font:700 22px/1.1 Georgia,serif; }}
    article p {{ color:var(--muted); margin:0 0 18px; }}
    .domain {{ color:var(--accent); font-size:12px; font-weight:750; letter-spacing:.06em; text-transform:uppercase; }}
    .tags {{ display:flex; gap:6px; flex-wrap:wrap; margin-top:auto; }}
    .tag {{ color:var(--muted); border:1px solid var(--line); border-radius:999px; padding:3px 8px; font-size:12px; }}
    .links {{ display:flex; gap:14px; border-top:1px solid var(--line); margin-top:16px; padding-top:12px; }}
    a {{ color:var(--ink); text-underline-offset:3px; }}
    .empty {{ color:var(--muted); padding:40px 0; }}
    @media (max-width:640px) {{ header {{ grid-template-columns:1fr; }} .controls {{ grid-template-columns:1fr; }} main {{ padding-top:28px; }} }}
  </style>
</head>
<body>
  <main>
    <header>
      <div><div class="eyebrow">Personal reference library</div><h1>Bookmarks</h1></div>
      <div class="count" id="count"></div>
    </header>
    <div class="controls"><input id="search" type="search" placeholder="Search titles, notes, domains, and tags"><button id="clear" type="button">Clear</button></div>
    <nav class="filters" id="filters" aria-label="Categories"></nav>
    <section class="grid" id="grid"></section>
    <div class="empty" id="empty" hidden>No bookmarks match this view.</div>
  </main>
  <script id="bookmark-data" type="application/json">{payload}</script>
  <script>
    const data = JSON.parse(document.getElementById('bookmark-data').textContent);
    const state = {{ query: '', category: 'all' }};
    const grid = document.getElementById('grid');
    const count = document.getElementById('count');
    const empty = document.getElementById('empty');
    const filters = document.getElementById('filters');
    function node(name, className, text) {{ const el=document.createElement(name); if(className) el.className=className; if(text!==undefined) el.textContent=text; return el; }}
    function renderFilters() {{
      filters.replaceChildren();
      const choices = [['all','All'], ...Object.entries(data.categories)];
      for (const [slug,label] of choices) {{ const b=node('button',state.category===slug?'active':'',label); b.type='button'; b.onclick=()=>{{state.category=slug; render();}}; filters.append(b); }}
    }}
    function render() {{
      const q=state.query.trim().toLowerCase();
      const items=data.items.filter(item => (state.category==='all'||item.categories.includes(state.category)) && (!q||[item.title,item.domain,item.summary,...item.tags,...item.categories].join(' ').toLowerCase().includes(q)));
      grid.replaceChildren();
      for (const item of items) {{
        const card=node('article'); card.append(node('div','domain',item.domain),node('h2','',item.title));
        if(item.summary) card.append(node('p','',item.summary));
        const tags=node('div','tags'); for(const tag of item.tags) tags.append(node('span','tag',tag)); card.append(tags);
        const links=node('div','links'); const source=node('a','', 'Open source'); source.href=item.url; source.target='_blank'; source.rel='noreferrer'; const note=node('a','','Open note'); note.href=item.note; links.append(source,note); card.append(links); grid.append(card);
      }}
      count.textContent=`${{items.length}} of ${{data.items.length}} bookmark${{data.items.length===1?'':'s'}}`;
      empty.hidden=items.length!==0; renderFilters();
    }}
    document.getElementById('search').addEventListener('input',event=>{{state.query=event.target.value;render();}});
    document.getElementById('clear').onclick=()=>{{state.query='';state.category='all';document.getElementById('search').value='';render();}};
    render();
  </script>
</body>
</html>
'''
    output.write_text(document, encoding="utf-8")
    print(f"Generated visualizer for {len(items)} bookmark(s): {output}")


def note_section(path: Path, heading: str, limit: int = 420) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(rf"^## {re.escape(heading)}\s*\n+(.*?)(?=\n## |\Z)", text, flags=re.MULTILINE | re.DOTALL)
    if not match:
        return ""
    paragraph = re.split(r"\n\s*\n", match.group(1).strip(), maxsplit=1)[0]
    paragraph = re.sub(r"\*\*Inference, not confirmed:\*\*\s*", "", paragraph, flags=re.IGNORECASE)
    paragraph = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", paragraph)
    paragraph = re.sub(r"[*_`]", "", paragraph)
    return re.sub(r"\s+", " ", paragraph).strip()[:limit]


def context_source_labels(config: dict[str, Any]) -> list[str]:
    context = config.get("context", {})
    if not isinstance(context, dict) or context.get("mode") == "none":
        return []
    labels: list[str] = []
    for source in context.get("sources", []):
        if isinstance(source, dict) and source.get("label"):
            labels.append(str(source["label"]))
        elif isinstance(source, str) and source.strip():
            labels.append(source.strip())
    return labels


def visualizer_media_url(root: Path, output: Path, value: Any) -> str:
    raw = str(value or "").strip()
    if not raw or raw.startswith(("http://", "https://", "data:")):
        return raw
    target = root / raw
    return os.path.relpath(target, start=output.parent).replace(os.sep, "/")


def visualize(root: Path, config: dict[str, Any]) -> None:
    visualizer_config = config.get("visualizer", {"enabled": False, "path": "visualizer/index.html"})
    if not visualizer_config.get("enabled", False):
        raise SystemError("The visualizer is disabled in config.json")
    output = root / visualizer_config.get("path", "visualizer/index.html")
    output.parent.mkdir(parents=True, exist_ok=True)
    categories = {item["slug"]: item["label"] for item in config["categories"]}
    items: list[dict[str, Any]] = []
    for record in bookmark_records(root, config):
        metadata = record["metadata"]
        preview_image = visualizer_media_url(
            root,
            output,
            metadata.get("preview_image") or metadata.get("preview_image_url"),
        )
        items.append(
            {
                "title": str(metadata.get("title") or record["path"].stem),
                "url": str(metadata.get("url") or ""),
                "domain": str(metadata.get("domain") or ""),
                "captured": str(metadata.get("captured") or ""),
                "categories": metadata.get("categories", []) if isinstance(metadata.get("categories"), list) else [],
                "tags": metadata.get("tags", []) if isinstance(metadata.get("tags"), list) else [],
                "summary": note_section(record["path"], "What it is", 280),
                "why": note_section(record["path"], "Why I may have saved it"),
                "contextBasis": metadata.get("context_basis", []) if isinstance(metadata.get("context_basis"), list) else [],
                "previewImage": preview_image,
                "previewImageAlt": str(metadata.get("preview_image_alt") or ""),
                "mediaType": str(metadata.get("media_type") or ("image" if preview_image else "none")),
                "embedUrl": str(metadata.get("embed_url") or ""),
                "videoUrl": str(metadata.get("video_url") or ""),
                "ticker": str(metadata.get("ticker") or ""),
                "note": os.path.relpath(record["path"], start=output.parent).replace(os.sep, "/"),
            }
        )
    context = config.get("context", {}) if isinstance(config.get("context"), dict) else {}
    rich_media = config.get("rich_media", {}) if isinstance(config.get("rich_media"), dict) else {}
    payload = json.dumps(
        {
            "items": items,
            "categories": categories,
            "ownerLabel": config.get("owner_label", "you"),
            "platform": config.get("agentic_platform", ""),
            "contextMode": context.get("mode", "none"),
            "contextSources": context_source_labels(config),
            "richMedia": {
                "enabled": rich_media.get("enabled", True),
                "allowRemoteVideoEmbeds": rich_media.get("allow_remote_video_embeds", False),
                "allowRemoteStockCharts": rich_media.get("allow_remote_stock_charts", False),
                "stockChartProvider": rich_media.get("stock_chart_provider", "tradingview"),
            },
        },
        ensure_ascii=False,
    ).replace("<", "\\u003c")
    assets_dir = Path(__file__).resolve().parent.parent / "assets"
    template_path = assets_dir / "visualizer-template.html"
    if not template_path.is_file():
        raise SystemError(f"Missing visualizer template: {template_path}")
    logo_path = assets_dir / "interzekt-logo.png"
    logo_data = ""
    if logo_path.is_file():
        logo_data = "data:image/png;base64," + base64.b64encode(logo_path.read_bytes()).decode("ascii")
    background_path = assets_dir / "visualizer-background.jpg"
    background_data = ""
    if background_path.is_file():
        background_data = "data:image/jpeg;base64," + base64.b64encode(background_path.read_bytes()).decode("ascii")
    document = (
        template_path.read_text(encoding="utf-8")
        .replace("__BOOKMARK_PAYLOAD__", payload)
        .replace("__INTERZEKT_LOGO__", logo_data)
        .replace("__BACKGROUND_IMAGE__", background_data)
    )
    output.write_text(document, encoding="utf-8")
    print(f"Generated visualizer for {len(items)} bookmark(s): {output}")


def validate(root: Path, config: dict[str, Any]) -> int:
    errors: list[str] = []
    warnings: list[str] = []
    paths = config["paths"]
    expected_dirs = [root / paths[name] for name in ("bookmarks", "views", "collections")]
    for directory in expected_dirs:
        if not directory.is_dir():
            errors.append(f"Missing directory: {directory}")
    index_path = root / paths["index"]
    if not index_path.is_file():
        errors.append(f"Missing index: {index_path}")
    elif index_path.read_text(encoding="utf-8").splitlines()[:1] != [MARKER]:
        warnings.append(f"Index is not generated: {index_path}")
    visualizer_config = config.get("visualizer", {"enabled": False})
    if visualizer_config.get("enabled", False):
        visualizer_path = root / visualizer_config.get("path", "visualizer/index.html")
        if not visualizer_path.is_file():
            errors.append(f"Missing enabled visualizer: {visualizer_path}")

    configured_categories = {category["slug"] for category in config["categories"]}
    seen_urls: dict[str, Path] = {}
    try:
        records = bookmark_records(root, config)
    except SystemError as exc:
        errors.append(str(exc))
        records = []

    for record in records:
        path = record["path"]
        metadata = record["metadata"]
        missing = sorted(REQUIRED_FIELDS - metadata.keys())
        if missing:
            errors.append(f"{path}: missing {', '.join(missing)}")
        if metadata.get("type") != "web-bookmark":
            errors.append(f"{path}: type must be web-bookmark")
        if metadata.get("status") != "bookmarked":
            errors.append(f"{path}: status must be bookmarked")
        if metadata.get("captured") and not DATE_RE.fullmatch(str(metadata["captured"])):
            errors.append(f"{path}: captured must be YYYY-MM-DD")
        for field in ("tags", "categories"):
            values = metadata.get(field)
            if not isinstance(values, list) or not values:
                errors.append(f"{path}: {field} must be a non-empty list")
            elif any(not SLUG_RE.fullmatch(str(value)) for value in values):
                errors.append(f"{path}: {field} contains a non-slug value")
        for category in metadata.get("categories", []) if isinstance(metadata.get("categories"), list) else []:
            if category not in configured_categories:
                errors.append(f"{path}: unknown category {category!r}")
        for field in ("url", "canonical_url", "original_url"):
            value = metadata.get(field)
            if not value:
                continue
            normalized = str(value).rstrip("/")
            if normalized in seen_urls and seen_urls[normalized] != path:
                errors.append(f"Duplicate {field} in {seen_urls[normalized]} and {path}")
            else:
                seen_urls[normalized] = path
        tags = metadata.get("tags", [])
        if isinstance(tags, list) and not 3 <= len(tags) <= 8:
            warnings.append(f"{path}: expected 3–8 tags, found {len(tags)}")
        media_type = str(metadata.get("media_type") or "none")
        if media_type not in MEDIA_TYPES:
            errors.append(f"{path}: media_type must be one of {', '.join(sorted(MEDIA_TYPES))}")
        preview_image = str(metadata.get("preview_image") or "").strip()
        if preview_image:
            preview_path = Path(preview_image)
            if preview_path.is_absolute() or ".." in preview_path.parts:
                errors.append(f"{path}: preview_image must be a root-relative safe path")
            elif not (root / preview_path).is_file():
                warnings.append(f"{path}: cached preview image is missing: {preview_image}")
        embed_url = str(metadata.get("embed_url") or "").strip()
        if embed_url:
            embed = urlsplit(embed_url)
            if embed.scheme != "https" or (embed.hostname or "").lower() not in EMBED_HOSTS:
                errors.append(f"{path}: embed_url is not an approved HTTPS provider")
        ticker = str(metadata.get("ticker") or "").strip()
        if ticker and (media_type != "stock" or not TICKER_RE.fullmatch(ticker)):
            errors.append(f"{path}: ticker requires media_type stock and an exchange-qualified symbol")

    for warning in warnings:
        print(f"WARNING: {warning}")
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if errors:
        print(f"Validation failed with {len(errors)} error(s) and {len(warnings)} warning(s).", file=sys.stderr)
        return 1
    print(f"Validation passed for {len(records)} bookmark(s) with {len(warnings)} warning(s).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("rebuild", "visualize", "validate"))
    parser.add_argument("root", type=Path, help="Bookmark-system root directory")
    args = parser.parse_args()
    root = args.root.expanduser().resolve()
    try:
        config = load_config(root)
        if args.command == "rebuild":
            rebuild(root, config)
            return 0
        if args.command == "visualize":
            visualize(root, config)
            return 0
        return validate(root, config)
    except SystemError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
